/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/repos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List repositories
     * @description Served from the scan snapshot ([`crate::cache::ScanCache`]), not the
     *     response cache — the list has no single backing repository, so its `ETag`
     *     is a hash of the serialized body. `sort` changes the body and therefore
     *     the `ETag`, so no extra cache-key work is needed for it.
     */
    get: operations["list_repos"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Repository summary
     * @description An empty repository (unborn HEAD) still answers `200`, with `head`,
     *     `default_branch` and `last_modified` `null` and both counts 0.
     */
    get: operations["get_repo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/archive/{ref}.{format}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Source archive
     * @description Streams `git archive` output chunked (no `Content-Length`). The ref is
     *     resolved first and only the **full sha** reaches the command line.
     *     `{ref}.{format}` is split by matching a known format suffix.
     */
    get: operations["get_archive"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/blame/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Per-line attribution
     * @description `{ref}`/`{path}` split as for the tree endpoint. Rename tracking is not
     *     performed — only moves within the file are attributed, per libgit2
     *     defaults.
     */
    get: operations["get_blame"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/blob/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * File metadata and content
     * @description `{ref}`/`{path}` split as for the tree endpoint. Binary or over-1 MiB files
     *     report `content: null` — fetch the raw endpoint instead.
     */
    get: operations["get_blob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/commits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Commit log
     * @description Cursor-paginated, newest first. Merge commits survive the `path` filter
     *     only when the path differs from **every** parent — an approximation of
     *     `git log -- <path>` simplification. `follow=1` extends the `path` filter
     *     across whole-file renames (cgit's `enable-follow-links`). `stat=1` adds
     *     each entry's first-parent file/line counts.
     */
    get: operations["list_commits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/commits/{sha}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Commit detail
     * @description Superset of a log entry, plus the full message and the first-parent
     *     diffstat. The diffstat has no file cap.
     */
    get: operations["get_commit"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/commits/{sha}/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Structured commit diff
     * @description Unified diff as JSON (file → hunk → line), against the first parent.
     *     Caps: 1000 rendered lines per file (whole hunks are dropped, never cut) and
     *     300 files per response; `additions`/`deletions` stay complete either way.
     */
    get: operations["get_commit_diff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Two-revision diff
     * @description Arbitrary two-revision diff (`git diff <from> <to>`), the same structured
     *     shape as the per-commit diff plus an uncapped `diffstat`. `?to=X` alone
     *     (no `from`) produces `files` identical to `GET /commits/X/diff`. `from`
     *     and `to` accept anything `resolve_commit` does — branch, tag, sha, or a
     *     `revparse_single` expression such as `main~1`. `?stat=1` skips hunk
     *     rendering entirely (cgit's `dt=2`), returning only the uncapped
     *     `diffstat`.
     */
    get: operations["get_rev_diff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/feed.atom": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Atom feed of recent commits
     * @description The most recent commits on `ref` (HEAD by default), 20 entries by
     *     default. `all=1` walks every branch and tag instead. Absolute URLs are
     *     reconstructed from `X-Forwarded-Proto`/`X-Forwarded-Host`, falling back
     *     to `Host`; entry ids are `urn:sha1:{sha}` so they stay stable across
     *     hosts. An empty repository, or `all=1` on a repository with no refs,
     *     returns `200` with no entries.
     */
    get: operations["get_feed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/objects/{oid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Object detail, by id
     * @description Every other route in this API resolves an object through a ref (and, for
     *     trees/blobs, a path); this is the one exception. `{oid}` must be a full
     *     40-character hex object id — abbreviations are rejected, since every
     *     link axgit itself emits carries a full oid, and requiring one is what
     *     lets this endpoint be unconditionally immutable-cached (the address pins
     *     the content, unlike `GET /tags/{name}`). Only the `type`-matching payload
     *     (`tree`/`blob`/`tag`) is non-null; a commit has none — link to
     *     `GET /commits/{sha}` instead.
     */
    get: operations["get_object"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/objects/{oid}/raw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Raw object bytes, by id
     * @description The by-oid analogue of `GET /raw/{ref}/{path}` — blob bytes only, any
     *     other kind is `404 object_not_found`. With no filename behind an oid
     *     there's no extension to guess a `Content-Type` from, so it's always
     *     `text/plain; charset=utf-8` or `application/octet-stream`.
     */
    get: operations["get_object_raw"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/patch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Format-patch series
     * @description `git format-patch`-style mbox series for the commit range `(from, to]` —
     *     `from` **excluded**, the opposite convention from `/diff`/`/rawdiff`.
     *     Every commit is diffed against its own first parent, including merges
     *     (`git format-patch` itself skips merges; every other axgit diff is
     *     first-parent, so this endpoint stays consistent with those instead).
     *     Rejects (`400`) rather than truncates a range over
     *     [`crate::repo::diff::MAX_PATCH_COMMITS`] commits. For `git am`.
     *
     *     Includes the author's name and email in `From:` headers — required for
     *     `git am` to preserve authorship, and the one axgit response that exposes a
     *     plain email address (docs/DECISIONS.md #38). Marked `noindex, nofollow`.
     */
    get: operations["get_patch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/raw/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Raw file contents
     * @description No size cap. Not routed through the response cache — raw bodies are
     *     unbounded binaries that would crowd out the JSON entries. Non-sha requests
     *     still carry an `ETag` so a 304 saves the transfer (the bytes are re-read
     *     either way). `{ref}`/`{path}` split as for the tree endpoint.
     */
    get: operations["get_raw"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/rawdiff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Raw unified diff
     * @description Plain unified diff between two revisions (`git diff <from> <to>`, the same
     *     two-dot semantics as `GET /diff` — not a merge-base `...` diff), for
     *     `git apply`. **No line/file caps** — unlike the structured diffs, a
     *     truncated patch would be a corrupt one. Has no `stat` mode — an empty diff
     *     with a stat summary elsewhere wouldn't be a valid patch.
     */
    get: operations["get_rawdiff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/readme": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * README lookup
     * @description Searches the root tree for `README.md` → `README.rst` → `README.txt` →
     *     `README`, matched case-insensitively. Symlinks and binary or over-1 MiB
     *     candidates are skipped. Rendering is the frontend's job.
     */
    get: operations["get_readme"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/refs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Branches and tags
     * @description Tag targets are peeled to the commit, so an annotated tag reports the
     *     commit sha rather than the tag object. `remote_branches` is `[]` on
     *     essentially every repository — see its field doc.
     */
    get: operations["get_refs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Repository search
     * @description git2 in-process scan across file content, file paths, commit messages,
     *     author/committer names, or a rev-list expression (docs/DECISIONS.md
     *     #26/#46) — not a `git grep`/`git log` exec or a persistent index. Every
     *     scan is bounded by its own byte/file/commit budget independent of
     *     `limit`; either cap sets `truncated: true`.
     */
    get: operations["get_search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Commit-activity statistics
     * @description Buckets commits into 12 `period`-sized windows anchored on the resolved
     *     commit's authordate (docs/DECISIONS.md #28), plus a per-author breakdown.
     *     git2 in-process scan, same budget approach as search (#26) — not a
     *     persistent index or a `git log` exec.
     */
    get: operations["get_stats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/tags/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Tag detail
     * @description Full tag message, tagger, and the tag's one-level dereferenced target —
     *     closes the gap `GET /refs` leaves open (`tags[].annotation` is only the
     *     first line, and `tags[].target` is already the fully peeled commit).
     *     Only a real tag name resolves here: a branch name, a commit sha, or
     *     `HEAD` all answer `404 ref_not_found` — only `refs/tags/{name}` is
     *     consulted.
     */
    get: operations["get_tag"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/tree/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Directory listing
     * @description The `{ref}`/`{path}` boundary is resolved per request by longest-ref
     *     matching (`repo::resolve::resolve_ref_path`), because branch and tag names
     *     may contain `/`; with no match the first segment is taken as the ref.
     *     Omit `{path}` for the root tree.
     */
    get: operations["get_tree"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{repo_git}/git-receive-pack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Push is SSH-only (CLAUDE.md invariant): every method on this path is 403. */
    post: operations["receive_pack"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{repo_git}/git-upload-pack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload-pack negotiation (clone/fetch)
     * @description Pipes the request body into `git upload-pack --stateless-rpc` and streams
     *     its stdout back chunked. If upload-pack dies mid-stream the status code
     *     cannot change, so the client sees an early EOF.
     */
    post: operations["upload_pack"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{repo_git}/info/refs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ref advertisement (clone/fetch)
     * @description Spawns `git upload-pack --stateless-rpc --advertise-refs` and prepends the
     *     pkt-line service header. A `Git-Protocol` request header is sanitized and
     *     forwarded as `GIT_PROTOCOL`, so protocol v2 negotiation works.
     */
    get: operations["info_refs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Per-author breakdown (docs/API.md). */
    AuthorStats: {
      author: components["schemas"]["CommitAuthor"];
      /** @description Total commits by this author within the window. */
      commits: number;
      /** @description Parallel to the response's `buckets` — same length and order. */
      buckets: number[];
    };
    /** @description Response of the blame endpoint (docs/API.md). */
    BlameInfo: {
      /** @description Resolved commit sha the file was blamed at. */
      sha: string;
      path: string;
      /** @description libgit2's NUL heuristic, or content that is not valid UTF-8. */
      binary: boolean;
      /** @description `true` past the same 1 MiB cap the blob endpoint applies. */
      too_large: boolean;
      /** @description Total line count; 0 for `binary`, `too_large`, or empty files. */
      lines: number;
      /**
       * @description `start_line` ascending, covering the whole file with no gaps.
       *     Empty for `binary`, `too_large`, or empty files.
       */
      ranges: components["schemas"]["BlameRange"][];
    };
    /** @description One contiguous run of lines attributed to the same commit (docs/API.md). */
    BlameRange: {
      /** @description 1-based, inclusive. */
      start_line: number;
      line_count: number;
      /** @description Sha of the commit the lines are attributed to. */
      sha: string;
      /** @description `None` for non-utf8 commit messages. */
      summary: string | null;
      author: components["schemas"]["CommitAuthor"];
      authored_at: string | null;
      /**
       * @description Path the lines had in the attributed commit, when the file has since
       *     been renamed — `None` when unchanged (or when the path is not valid
       *     UTF-8). Only whole-file renames are tracked; libgit2 follows them the
       *     same way `git blame` does by default.
       */
      orig_path: string | null;
    };
    /** @description Response of the blob endpoint (docs/API.md). */
    BlobInfo: {
      /** @description Resolved commit sha the blob was read from. */
      sha: string;
      path: string;
      /**
       * @description Octal file mode, e.g. `"100644"` (`"120000"` for symlinks).
       * @example 100644
       */
      mode: string;
      /**
       * Format: int64
       * @description Full size in bytes, regardless of `too_large`.
       */
      size: number;
      /** @description libgit2's NUL heuristic, or content that is not valid UTF-8. */
      binary: boolean;
      /** @description `true` past the 1 MiB inline-content cap; fetch the raw endpoint instead. */
      too_large: boolean;
      /**
       * @description UTF-8 content; `None` when `binary` or `too_large`. For a symlink this
       *     is the link target path.
       */
      content: string | null;
    };
    /** @description Branch entry of `GET /api/v1/repos/{repo}/refs` (docs/API.md). */
    BranchRef: {
      /** @example main */
      name: string;
      /** @description Commit sha of the branch tip. */
      target: string;
      /** @description Authordate (RFC 3339) of the branch tip. */
      committed_at: string | null;
    };
    /** @description One time bucket (docs/API.md). */
    BucketStats: {
      /** @description Bucket start, UTC, RFC 3339. Ascending order (oldest first). */
      start: string;
      /** @description Total commits in this bucket, including any authors cut by `limit`. */
      commits: number;
    };
    /**
     * @description Commit author of `GET /api/v1/repos/{repo}/commits` (docs/API.md).
     *     The raw email is never exposed; `email_hash` seeds locally generated avatars.
     */
    CommitAuthor: {
      name: string;
      /**
       * @description sha256 hex of the trimmed, lowercased author email.
       * @example b642b4217b34b1e8d3bd915fc65c4452
       */
      email_hash: string;
    };
    /**
     * @description Commit detail of `GET /api/v1/repos/{repo}/commits/{sha}` (docs/API.md).
     *     Superset of [`CommitInfo`] so the frontend can extend the log entry type.
     */
    CommitDetail: {
      /** @description Full commit sha, even when the request used a branch, tag or short sha. */
      sha: string;
      summary: string | null;
      /** @description Full commit message. `None` for non-utf8 messages. */
      message: string | null;
      /**
       * @description `git notes` message attached to this commit on the repository's
       *     default notes ref (`refs/notes/commits`, or `core.notesRef` when set).
       *     `None` when there is no note, no notes ref at all, or the note is
       *     non-utf8 or blank. Only the default ref is read — cgit's
       *     `notes.displayRef`/multi-ref concatenation has no analogue here.
       */
      note: string | null;
      author: components["schemas"]["CommitAuthor"];
      committer: components["schemas"]["CommitAuthor"];
      authored_at: string | null;
      committed_at: string | null;
      parents: string[];
      /** @description First-parent diffstat (docs/API.md). */
      diffstat: components["schemas"]["DiffStat"];
    };
    /** @description Structured diff of `GET /api/v1/repos/{repo}/commits/{sha}/diff` (docs/API.md). */
    CommitDiff: {
      sha: string;
      /** @description First parent the diff was computed against; `null` for a root commit. */
      parent: string | null;
      /** @description `true` when files beyond [`MAX_DIFF_FILES`] were omitted. */
      truncated: boolean;
      files: components["schemas"]["FileDiff"][];
    };
    /** @description Log entry of `GET /api/v1/repos/{repo}/commits` (docs/API.md). */
    CommitInfo: {
      /** @description Full commit sha. */
      sha: string;
      /** @description First line of the commit message. `None` for non-utf8 commit messages. */
      summary: string | null;
      /**
       * @description Commit message past the summary line, trimmed. Present only when the
       *     request asked for it (`msg=1`); the key itself is omitted otherwise,
       *     for a commit with no body, and for a non-utf8 message.
       */
      body?: string | null;
      author: components["schemas"]["CommitAuthor"];
      /**
       * @description Authordate (RFC 3339). `None` for unrepresentable timestamps.
       * @example 2026-07-01T14:00:00+09:00
       */
      authored_at: string | null;
      parents: string[];
      /**
       * @description The path filter's previous name, when this commit is the rename this
       *     entry was followed across (`follow=1`, docs/DECISIONS.md #56). Present
       *     only on the renaming commit itself, never on the commits before or
       *     after it — the key is omitted, not `null`, everywhere else (same rule
       *     as `body`, #44).
       */
      renamed_from?: string | null;
      stat?: null | components["schemas"]["StatCounts"];
    };
    CommitsPage: {
      commits: components["schemas"]["CommitInfo"][];
      /**
       * @description Opaque token for the next page; `null` on the last page. Pass it back
       *     verbatim as the `cursor` query parameter.
       */
      next_cursor: string | null;
    };
    /** @description Diffstat of `GET /api/v1/repos/{repo}/commits/{sha}` (docs/API.md). */
    DiffStat: {
      files: components["schemas"]["DiffStatFile"][];
      files_changed: number;
      total_additions: number;
      total_deletions: number;
    };
    /** @description Per-file entry shared by the diffstat and the diff (`#[serde(flatten)]`). */
    DiffStatFile: {
      /** @example src/main.rs */
      path: string;
      /** @description Previous path; only set for `renamed`/`copied`. */
      old_path: string | null;
      status: components["schemas"]["DiffStatus"];
      /**
       * @description Always the full count, even when the file's hunks were truncated.
       *     Binary files report 0.
       */
      additions: number;
      /**
       * @description Always the full count, even when the file's hunks were truncated.
       *     Binary files report 0.
       */
      deletions: number;
      binary: boolean;
    };
    /**
     * @description How a file changed between the two trees. Rename detection runs with
     *     libgit2 defaults (renames only, 50% similarity).
     * @enum {string}
     */
    DiffStatus: "added" | "deleted" | "modified" | "renamed" | "copied" | "typechange";
    /**
     * @description What a tree entry points at, derived from its file mode.
     * @enum {string}
     */
    EntryKind: "tree" | "blob" | "symlink" | "commit";
    ErrorBody: {
      /**
       * @description One of `repo_not_found`, `ref_not_found`, `path_not_found`,
       *     `object_not_found`, `invalid_param`, `read_only`, `not_found`,
       *     `internal`.
       * @example repo_not_found
       */
      code: string;
      /**
       * @description Human-readable detail. Internal errors report a generic message; the
       *     cause only goes to the server log.
       * @example repository 'foo' not found
       */
      message: string;
    };
    /** @description Error envelope shared by every failing endpoint (docs/API.md). */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    FileDiff: components["schemas"]["DiffStatFile"] & {
      /**
       * @description `true` when hunks were dropped past [`MAX_FILE_DIFF_LINES`].
       *     `additions`/`deletions` still count the full change.
       */
      truncated: boolean;
      /** @description Empty for binary files. */
      hunks: components["schemas"]["Hunk"][];
    };
    /** @description A file with at least one match (docs/API.md). */
    FileMatch: {
      path: string;
      /**
       * @description Empty for `type=path` matches — the path itself is the match, there is
       *     no line to point at.
       */
      lines: components["schemas"]["LineMatch"][];
    };
    Hunk: {
      /**
       * @description `@@ -a,b +c,d @@ <context>` line without the trailing newline.
       * @example @@ -1,2 +1,2 @@
       */
      header: string;
      /** Format: int32 */
      old_start: number;
      /** Format: int32 */
      old_lines: number;
      /** Format: int32 */
      new_start: number;
      /** Format: int32 */
      new_lines: number;
      lines: components["schemas"]["Line"][];
    };
    Line: {
      origin: components["schemas"]["LineOrigin"];
      /** @description Line content without the trailing newline (lossy utf-8). */
      content: string;
      /**
       * Format: int32
       * @description `null` on added lines.
       */
      old_lineno: number | null;
      /**
       * Format: int32
       * @description `null` on deleted lines.
       */
      new_lineno: number | null;
    };
    /** @description Matched line within a file (docs/API.md). */
    LineMatch: {
      /** @description 1-based line number. */
      line: number;
      /** @description The matching line, truncated to [`MAX_LINE_CHARS`] characters. */
      text: string;
    };
    /**
     * @description Which side of the diff a line belongs to. Other libgit2 origins (EOF
     *     newline markers and the like) are dropped rather than reported.
     * @enum {string}
     */
    LineOrigin: " " | "+" | "-";
    /**
     * @description Blob payload of the object endpoint. Same fields as `BlobInfo`
     *     (`repo::blob`) minus `sha`/`path`/`mode` — an oid alone has neither a
     *     path nor a mode; mode lives on the tree entry that references it.
     */
    ObjectBlob: {
      /**
       * Format: int64
       * @description Full size in bytes, regardless of `too_large`.
       */
      size: number;
      /** @description libgit2's NUL heuristic, or content that is not valid UTF-8. */
      binary: boolean;
      /** @description `true` past the 1 MiB inline-content cap; fetch `.../raw` instead. */
      too_large: boolean;
      /** @description UTF-8 content; `None` when `binary` or `too_large`. */
      content: string | null;
    };
    /**
     * @description Response of `GET /objects/{oid}` (docs/API.md). Every key is always
     *     present (this document's general rule) rather than a `oneOf` union — one
     *     envelope, with only the `type`-matching payload populated.
     */
    ObjectDetail: {
      sha: string;
      type: components["schemas"]["ObjectKind"];
      tree: null | components["schemas"]["ObjectTree"];
      blob: null | components["schemas"]["ObjectBlob"];
      tag: null | components["schemas"]["ObjectTag"];
    };
    /**
     * @description What kind of object a tag's one-level dereference points at. Deliberately
     *     separate from `tree::EntryKind` — that enum's domain is tree entries (it
     *     carries `symlink`, and its `commit` variant means gitlink), not tag
     *     targets.
     * @enum {string}
     */
    ObjectKind: "commit" | "tree" | "blob" | "tag";
    /**
     * @description Tag payload of the object endpoint — a nested tag's own detail, same
     *     shape and rules `GET /tags/{name}` reports, minus `name`/`tag_object`
     *     (an oid alone has neither a ref name nor a need to restate its own sha,
     *     already reported as the envelope's `sha`).
     */
    ObjectTag: {
      /** @description One-level dereference of this tag (see `repo::tag::TagObject`). */
      object: components["schemas"]["TagObject"];
      /** @description Fully peeled commit sha. `None` when the chain never reaches one. */
      target: string | null;
      /**
       * @description Full tag message, trailing whitespace trimmed. `None` for a
       *     non-utf8 or all-whitespace message.
       */
      message: string | null;
      tagger: null | components["schemas"]["CommitAuthor"];
      tagged_at: string | null;
    };
    /**
     * @description Tree payload of the object endpoint. Entries link onward by their own
     *     `sha` (`TreeEntryInfo::sha`) — there's no root commit here to build a
     *     path from, so by-oid navigation is oid-to-oid rather than path-based.
     */
    ObjectTree: {
      /** @description Trees first, then by name ascending — same ordering as `GET /tree`. */
      entries: components["schemas"]["TreeEntryInfo"][];
    };
    /**
     * @description Aggregate of the authors cut by `limit` (docs/API.md), so the visible rows
     *     plus this one always reconcile with the bucket totals.
     */
    OtherAuthors: {
      /** @description Authors folded in here — equals `author_count - authors.len()`. */
      count: number;
      /** @description Their combined commits within the window. */
      commits: number;
      /** @description Parallel to the response's `buckets`, summed elementwise. */
      buckets: number[];
    };
    /**
     * @description How the frontend should render the README. Only `markdown` is converted to
     *     HTML; the rest are shown as plain text (docs/DECISIONS.md #11).
     * @enum {string}
     */
    ReadmeFormat: "markdown" | "rst" | "plain";
    ReadmeInfo: {
      /**
       * @description Actual file name as it appears in the tree (case may differ).
       * @example README.md
       */
      path: string;
      format: components["schemas"]["ReadmeFormat"];
      content: string;
    };
    RefsInfo: {
      /** @description Sorted by name ascending; empty for a repository without commits. */
      branches: components["schemas"]["BranchRef"][];
      /**
       * @description Remote-tracking branches (`refs/remotes/*`), sorted by name ascending.
       *     Empty on essentially every repository axgit serves today: neither
       *     axgit nor the git-compose stack that populates `/srv/git` ever runs
       *     `git remote add`/`git fetch` against a served bare repository (pushes
       *     arrive via SSH only, CLAUDE.md's read-only invariant) — this field
       *     exists for the rare case of a repository someone configured that way
       *     by hand, not for anything axgit itself produces.
       */
      remote_branches: components["schemas"]["BranchRef"][];
      /** @description Sorted by name ascending. */
      tags: components["schemas"]["TagRef"][];
    };
    /** @description Repository list entry as defined by `GET /api/v1/repos` in docs/API.md. */
    RepoInfo: {
      /**
       * @description Repository name without the `.git` suffix.
       * @example git-compose
       */
      name: string;
      /** @description From the repo config's `[axgit]` section, falling back to `[cgit]`. */
      section: string | null;
      /** @description From the repo config's `[axgit]` section, falling back to `[cgit]`. */
      owner: string | null;
      /** @description From the repo config's `[axgit]` section, falling back to `[cgit]`. */
      description: string | null;
      /**
       * @description From the repo config's `homepage` key, same `[axgit]`/`[cgit]`
       *     precedence. `None` unless the configured value is a `http://` or
       *     `https://` URL — it lands in an `href`, so any other scheme (in
       *     particular `javascript:`) is dropped rather than served.
       * @example https://git.ptcookie.net
       */
      homepage: string | null;
      /** @description `None` for empty repositories (unborn HEAD). */
      default_branch: string | null;
      /**
       * @description Agefile (`info/web/last-modified`), falling back to the HEAD authordate.
       *     RFC 3339. `None` for empty repositories without an agefile.
       * @example 2026-07-24T13:06:00+09:00
       */
      last_modified: string | null;
    };
    /**
     * @description Repository summary as defined by `GET /api/v1/repos/{repo}` in docs/API.md.
     *     Kept separate from [`RepoInfo`] — the list and summary responses are
     *     distinct API contracts.
     */
    RepoSummary: {
      /** @example git-compose */
      name: string;
      section: string | null;
      owner: string | null;
      description: string | null;
      /** @example https://git.ptcookie.net */
      homepage: string | null;
      default_branch: string | null;
      /** @example 2026-07-24T13:06:00+09:00 */
      last_modified: string | null;
      /** @description HEAD commit sha. `None` for empty repositories (unborn HEAD). */
      head: string | null;
      /**
       * @description Local branches only — remote-tracking branches (`refs/remotes/*`,
       *     `RefsInfo.remote_branches`) are not counted here.
       */
      branch_count: number;
      tag_count: number;
      /** @description `{clone_url_base}/{name}.git`; `None` when no base is configured. */
      clone_url: string | null;
    };
    ReposResponse: {
      repos: components["schemas"]["RepoInfo"][];
      /**
       * @description The effective sort order actually applied — the request's `?sort=` if
       *     given, else the server's configured default. Lets a client mark the
       *     active column without knowing `AXGIT_REPOSITORY_SORT`.
       * @example name
       */
      sort: string;
    };
    /**
     * @description Two-revision diff of `GET /api/v1/repos/{repo}/diff` (docs/API.md). A
     *     plain tree-to-tree comparison (`git diff <from> <to>`), not a merge-base
     *     `...` diff.
     */
    RevDiff: {
      /**
       * @description Resolved full sha of the old side. `null` only when `from` was omitted
       *     and `to` is a root commit (the old side is then the empty tree).
       */
      from: string | null;
      /** @description Resolved full sha of the new side. */
      to: string;
      /**
       * @description `true` when files beyond [`MAX_DIFF_FILES`] were omitted. Always
       *     `false` in stat-only mode (`?stat=1`) — there is nothing to cap when
       *     `files` itself is always empty.
       */
      truncated: boolean;
      /** @description The full, uncapped file list — same rule as the commit diffstat. */
      diffstat: components["schemas"]["DiffStat"];
      /**
       * @description Always empty in stat-only mode (`?stat=1`, [`rev_diff_stat`]) — the
       *     caller only wanted `diffstat`, so hunks are never rendered.
       */
      files: components["schemas"]["FileDiff"][];
    };
    /**
     * @description Requested search variant, echoed back in the response's `type` field.
     * @enum {string}
     */
    SearchKind: "content" | "path" | "message" | "author" | "committer" | "range";
    /** @description Response of `GET /api/v1/repos/{repo}/search` (docs/API.md). */
    SearchResults: {
      /**
       * @description Resolved commit sha the search ran against. `None` only for an empty
       *     repository (unborn HEAD) with no explicit `ref`.
       */
      sha: string | null;
      type: components["schemas"]["SearchKind"];
      /**
       * @description `true` when a scan or result budget was hit before the search
       *     finished — the results are a prefix, not necessarily the complete
       *     match set.
       */
      truncated: boolean;
      /** @description `content`/`path` results; empty for `type=message`. */
      files: components["schemas"]["FileMatch"][];
      /**
       * @description `message` results; empty otherwise. Reuses the commit log's shape so
       *     the frontend can render matches the same way as log rows.
       */
      commits: components["schemas"]["CommitInfo"][];
    };
    /**
     * @description File/line counts for the commit log's `stat=1` column (cgit's
     *     `enable-log-filecount`/`enable-log-linecount`, docs/DECISIONS.md #57).
     */
    StatCounts: {
      files_changed: number;
      additions: number;
      deletions: number;
    };
    /**
     * @description Requested bucket size, echoed back in the response's `period` field.
     * @enum {string}
     */
    StatsPeriod: "week" | "month" | "quarter" | "year";
    /** @description Response of `GET /api/v1/repos/{repo}/stats` (docs/API.md). */
    StatsResults: {
      /**
       * @description Resolved commit sha the window is anchored on. `None` only for an
       *     empty repository (unborn HEAD) with no explicit `ref`.
       */
      sha: string | null;
      period: components["schemas"]["StatsPeriod"];
      /**
       * @description `true` when the commit scan budget was hit, or the author list was cut
       *     by `limit` — either way, the results are a prefix.
       */
      truncated: boolean;
      /**
       * @description Number of distinct authors within the window (may exceed
       *     `authors.len()` once cut by `limit`).
       */
      author_count: number;
      buckets: components["schemas"]["BucketStats"][];
      /** @description Sorted by commit count, descending; capped at `limit`. */
      authors: components["schemas"]["AuthorStats"][];
      others: null | components["schemas"]["OtherAuthors"];
    };
    /** @description Tag detail of `GET /api/v1/repos/{repo}/tags/{name}` (docs/API.md). */
    TagDetail: {
      /** @example v1.0.0 */
      name: string;
      /**
       * @description The annotated tag object's own sha. `None` for a lightweight tag —
       *     lightweight tags have no tag object, so `message`/`tagger`/`tagged_at`
       *     are `None` too and `object.sha == target`.
       */
      tag_object: string | null;
      /** @description One dereference of the tag (see [`TagObject`]). */
      object: components["schemas"]["TagObject"];
      /**
       * @description Fully peeled commit sha — the same value `GET /refs`' `tags[].target`
       *     reports. `None` when the tag chain never reaches a commit (a tag on a
       *     tree or blob), which is also exactly when an archive download is
       *     unavailable for this tag.
       */
      target: string | null;
      /**
       * @description Full tag message, trailing whitespace trimmed. `None` for a
       *     lightweight tag, a non-utf8 message, or an all-whitespace message.
       */
      message: string | null;
      tagger: null | components["schemas"]["CommitAuthor"];
      tagged_at: string | null;
    };
    /**
     * @description The object a tag points at, one dereference in. For an annotated tag this
     *     is the tag object's own `object` header; for a lightweight tag it's the
     *     ref's direct target. A nested tag (tag-of-tag) or a tag on a tree/blob
     *     reports that object here, not the fully peeled commit — see
     *     [`TagDetail::target`].
     */
    TagObject: {
      sha: string;
      type: components["schemas"]["ObjectKind"];
    };
    /** @description Tag entry of `GET /api/v1/repos/{repo}/refs` (docs/API.md). */
    TagRef: {
      /** @example v1.0.0 */
      name: string;
      /**
       * @description The tag's one-level dereference — same meaning as `GET /tags/{name}`'s
       *     `object` (docs/DECISIONS.md #51/#53).
       */
      object: components["schemas"]["TagObject"];
      /**
       * @description Fully peeled commit sha, same meaning as `GET /tags/{name}`'s
       *     `target`. `None` when the tag chain never reaches a commit (a tag on
       *     a tree or blob) — also exactly when an archive download and a
       *     Compare link are unavailable for this tag.
       */
      target: string | null;
      /** @description First line of the tag message. `None` for lightweight tags. */
      annotation: string | null;
      /** @description Tagger date (RFC 3339). `None` for lightweight tags. */
      tagged_at: string | null;
    };
    /** @description Tree entry of the tree endpoint (docs/API.md). */
    TreeEntryInfo: {
      name: string;
      type: components["schemas"]["EntryKind"];
      /**
       * @description Octal file mode, e.g. `"100644"`.
       * @example 100644
       */
      mode: string;
      /**
       * @description The entry's own object id — a gitlink entry's `sha` is the submodule
       *     commit in the *other* repository, not reachable through this one.
       *     Lets a by-oid object page (`GET /objects/{oid}`) link each row onward.
       */
      sha: string;
      /**
       * Format: int64
       * @description Object size in bytes; blobs only, `None` otherwise.
       */
      size: number | null;
      /**
       * @description Symlink target path; symlinks only, `None` otherwise — also `None` for
       *     a non-UTF-8 target or one past `SYMLINK_TARGET_LIMIT`. Relative to the
       *     entry's own directory, exactly as stored; clients resolve it.
       */
      target: string | null;
    };
    TreeListing: {
      /** @description Resolved commit sha the listing was taken from. */
      sha: string;
      /** @description Requested directory path; empty string for the root tree. */
      path: string;
      /** @description Trees first, then by name ascending. */
      entries: components["schemas"]["TreeEntryInfo"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_repos: {
    parameters: {
      query?: {
        /**
         * @description `name` (default), `desc`, `owner`, `idle`, or `section`, optionally
         *     prefixed with `-` to reverse direction (`idle` reverses to ascending
         *     under `-idle`, i.e. oldest first). Falls back to
         *     `AXGIT_REPOSITORY_SORT` (server default `name`) when absent.
         * @example idle
         */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository list */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Hash of the response body; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReposResponse"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — unknown `sort` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Repository root could not be scanned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_repo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository summary */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepoSummary"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description One of `tar.gz`, `tar.bz2`, `tar.xz`, `tar.zst`, `zip`
         * @example tar.gz
         */
        format: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archive stream (`application/gzip`, `application/x-bzip2`, `application/x-xz`, `application/zstd`, or `application/zip`). `tar.bz2`/`tar.xz`/`tar.zst` are produced by streaming `git archive`'s uncompressed tar output through an in-process encoder. If `git archive` fails mid-stream the response is truncated without a status change — for the three encoder formats this yields a well-formed compressed file wrapping a truncated tar, since the encoder still finalizes its container. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description `attachment; filename="{repo}-{safe_ref}.{format}"` */
          "Content-Disposition"?: string;
          /** @description **Weak** (`W/"..."`); absent on full-sha requests */
          ETag?: string;
          /** @description Always `nosniff` */
          "X-Content-Type-Options"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/gzip": string;
        };
      };
      /** @description `If-None-Match` matched — no git process is spawned */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — suffix is none of `.tar.gz`, `.tar.bz2`, `.tar.xz`, `.tar.zst`, `.zip` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `internal` — `git archive` could not be spawned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_blame: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description File path
         * @example src/main.rs
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Line ranges covering the whole file. Immutable caching only when `{ref}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlameInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_blob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description File path
         * @example README.md
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Blob metadata and inline content. Immutable caching only when `{ref}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlobInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` (missing, or a directory/submodule) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_commits: {
    parameters: {
      query?: {
        /**
         * @description Branch, tag, or commit sha; HEAD when absent. Ignored when `cursor` is set.
         * @example main
         */
        ref?: string;
        /**
         * @description Only commits that changed this file or directory. A path that never
         *     existed yields an empty list rather than a 404.
         */
        path?: string;
        /**
         * @description `next_cursor` from a previous page. Opaque: a malformed or unknown
         *     value is `400 invalid_param`, not a 404.
         */
        cursor?: string;
        /**
         * @description Parsed manually so an invalid value yields the JSON `invalid_param`
         *     envelope instead of axum's plain-text 400. Never clamped.
         * @example 50
         */
        limit?: number;
        /**
         * @description When `1`/`true`, each log entry also carries the commit message's
         *     `body` (past the summary line). Absent/`0`/`false` by default.
         */
        msg?: boolean;
        /**
         * @description When `1`/`true`, the `path` filter follows the file across whole-file
         *     renames (cgit's `enable-follow-links`). Ignored when `path` is absent.
         *     Absent/`0`/`false` by default.
         */
        follow?: boolean;
        /**
         * @description When `1`/`true`, each log entry also carries first-parent file/line
         *     counts (cgit's `enable-log-filecount`/`enable-log-linecount` merged
         *     into one flag). Absent/`0`/`false` by default.
         */
        stat?: boolean;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of commits. An empty repository with no `ref` yields an empty page. Immutable caching when `cursor` is given, or when `ref` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a `cursor` or full-sha `ref` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque. Absent on `cursor` and full-sha `ref` requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitsPage"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `limit` or `cursor` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_commit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /** @description Branch, tag, or commit sha */
        sha: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Commit detail. Immutable caching only when `{sha}` is the resolved full sha and the commit carries no `note` (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha with no note */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha, note-less requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitDetail"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_commit_diff: {
    parameters: {
      query?: {
        /**
         * @description Restrict the diff to one file (literal match, no globbing). A path that
         *     this commit did not touch yields `files: []`, not a 404.
         */
        path?: string;
        /**
         * @description Context lines around each change. Parsed manually so an invalid value
         *     yields the JSON `invalid_param` envelope instead of axum's plain-text
         *     400. Never clamped.
         * @example 3
         */
        context?: number;
        /**
         * @description Ignore whitespace-only changes (`git diff --ignore-all-space`). Line
         *     `content` is unaffected — only which lines/hunks are shown changes.
         * @example 1
         */
        ignorews?: boolean;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /** @description Branch, tag, or commit sha */
        sha: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Structured diff. Immutable caching only when `{sha}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitDiff"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `context` or `ignorews` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_rev_diff: {
    parameters: {
      query?: {
        /**
         * @description Old side of the comparison (`git diff <from> <to>` — not a merge-base
         *     `...` diff). Defaults to `to`'s first parent (the empty tree for a
         *     root commit).
         * @example main
         */
        from?: string;
        /**
         * @description New side of the comparison. Defaults to `HEAD`.
         * @example feature/x
         */
        to?: string;
        /**
         * @description Restrict the diff to one file (literal match, no globbing). A path
         *     neither side touched yields `files: []`, not a 404.
         */
        path?: string;
        /**
         * @description Context lines around each change. Parsed manually so an invalid value
         *     yields the JSON `invalid_param` envelope instead of axum's plain-text
         *     400. Never clamped.
         * @example 3
         */
        context?: number;
        /**
         * @description Ignore whitespace-only changes (`git diff --ignore-all-space`).
         * @example 1
         */
        ignorews?: boolean;
        /**
         * @description Skip hunk rendering — `files` stays empty and `truncated` stays
         *     `false`; only `diffstat` (already uncapped) is computed. `context`/
         *     `ignorews` have no effect in this mode.
         * @example 1
         */
        stat?: boolean;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Two-revision diff. Immutable caching only when every side given resolves to the exact requested string as a full sha. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent when immutable */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevDiff"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `context`, `ignorews`, or `stat` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` (names the offending side) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_feed: {
    parameters: {
      query?: {
        /**
         * @description Branch, tag, or commit sha; HEAD when absent. Ignored when `all=1`.
         * @example main
         */
        ref?: string;
        /**
         * @description Only commits that changed this file or directory. A path that never
         *     existed yields an entry-less feed rather than a 404. No `follow`
         *     support — unlike the commit log, the feed never tracks a path across
         *     renames (docs/DECISIONS.md #61).
         */
        path?: string;
        /**
         * @description `1`/`true` walks every local branch and tag (`refs/heads/*` +
         *     `refs/tags/*`) instead of just the selected `ref`, newest first by
         *     committer date. Any other value is `400 invalid_param`.
         */
        all?: boolean;
        /**
         * @description Number of entries, default 20. Parsed manually so an invalid value
         *     yields the JSON `invalid_param` envelope instead of axum's plain-text
         *     400. Never clamped.
         * @example 20
         */
        limit?: number;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Atom 1.0 feed */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/atom+xml": string;
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `all` or `limit` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_object: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Full 40-character hex object id
         * @example 94739392266bcbd2a4dcc7e02f57b7cf4ba7ec02
         */
        oid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Object detail. Always immutably cached — the address is the content. */
      200: {
        headers: {
          /** @description `public, max-age=31536000, immutable` */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObjectDetail"];
        };
      };
      /** @description `invalid_param` — `{oid}` is not a full 40-character hex id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `object_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_object_raw: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Full 40-character hex object id
         * @example 94739392266bcbd2a4dcc7e02f57b7cf4ba7ec02
         */
        oid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Blob bytes. Always immutably cached. */
      200: {
        headers: {
          /** @description `public, max-age=31536000, immutable` */
          "Cache-Control"?: string;
          /** @description Always `nosniff` — repository contents are untrusted */
          "X-Content-Type-Options"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description `invalid_param` — `{oid}` is not a full 40-character hex id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `object_not_found` (missing, or not a blob) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_patch: {
    parameters: {
      query?: {
        /**
         * @description Start of the commit range, **excluded** (`git format-patch
         *     <from>..<to>`) — unlike `from` on `/diff`/`/rawdiff`, which names the
         *     other side of a tree comparison. Omitted renders a single patch for
         *     `to` alone.
         * @example main
         */
        from?: string;
        /**
         * @description End of the range (inclusive). Defaults to `HEAD`.
         * @example feature/x
         */
        to?: string;
        /** @description Restrict every commit's diff to one file (literal match, no globbing). */
        path?: string;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description mbox-format patch series, no size limit. Immutable caching only when every side given resolves to the exact requested string as a full sha. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` */
          "Cache-Control"?: string;
          /** @description `inline; filename="{repo}-{safe_to}.patch"` */
          "Content-Disposition"?: string;
          /** @description Validator-derived; absent when immutable */
          ETag?: string;
          /** @description Always `nosniff` */
          "X-Content-Type-Options"?: string;
          /** @description Always `noindex, nofollow` */
          "X-Robots-Tag"?: string;
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — commit range exceeds the patch-count limit */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` (names the offending side) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_raw: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description File path
         * @example README.md
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File bytes. `Content-Type` is guessed from the extension, falling back to `text/plain; charset=utf-8` or `application/octet-stream`. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          /** @description Always `nosniff` — repository contents are untrusted */
          "X-Content-Type-Options"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_rawdiff: {
    parameters: {
      query?: {
        /**
         * @description Old side of the comparison (`git diff <from> <to>` — not a merge-base
         *     `...` diff). Defaults to `to`'s first parent (the empty tree for a
         *     root commit).
         * @example main
         */
        from?: string;
        /**
         * @description New side of the comparison. Defaults to `HEAD`.
         * @example feature/x
         */
        to?: string;
        /**
         * @description Restrict the diff to one file (literal match, no globbing). A path
         *     neither side touched yields an empty diff, not a 404.
         */
        path?: string;
        /**
         * @description Context lines around each change. Parsed manually so an invalid value
         *     yields the JSON `invalid_param` envelope instead of axum's plain-text
         *     400. Never clamped.
         * @example 3
         */
        context?: number;
        /**
         * @description Ignore whitespace-only changes (`git diff --ignore-all-space`).
         * @example 1
         */
        ignorews?: boolean;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Plain unified diff, no size limit. Immutable caching only when every side given resolves to the exact requested string as a full sha. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent when immutable */
          ETag?: string;
          /** @description Always `nosniff` */
          "X-Content-Type-Options"?: string;
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `context` or `ignorews` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` (names the offending side) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_readme: {
    parameters: {
      query?: {
        /**
         * @description Branch, tag, or commit sha; HEAD when absent.
         * @example main
         */
        ref?: string;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The first usable README. Immutable caching only when `ref` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadmeInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found`, `ref_not_found` (including an empty repository), `path_not_found` (no README) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_refs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Local branches, remote-tracking branches, and tags, each sorted by name */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefsInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_search: {
    parameters: {
      query?: {
        /**
         * @description Fixed-string, case-insensitive query for every `type` except `range`,
         *     where it is a case-sensitive rev-list expression instead. Trimmed;
         *     empty or over 200 characters is `invalid_param` either way.
         * @example TODO
         */
        q?: string;
        /**
         * @description `content` (default), `path`, `message`, `author`, `committer`, or
         *     `range`.
         * @example content
         */
        type?: string;
        /**
         * @description Branch, tag, or commit sha; HEAD when absent.
         * @example main
         */
        ref?: string;
        /**
         * @description Parsed manually so an invalid value yields the JSON `invalid_param`
         *     envelope instead of axum's plain-text 400. Never clamped.
         * @example 50
         */
        limit?: number;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Search results. An empty repository with no `ref` yields an empty result. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full-sha `ref` (never immutable for `type=range`) */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha `ref` requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResults"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — missing/oversized `q`, unknown `type`, bad `limit`, or a `range` token starting with `-` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` (also returned when a `range` token doesn't resolve) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_stats: {
    parameters: {
      query?: {
        /**
         * @description `week`, `month` (default), `quarter`, or `year`.
         * @example month
         */
        period?: string;
        /**
         * @description Branch, tag, or commit sha; HEAD when absent.
         * @example main
         */
        ref?: string;
        /**
         * @description Only commits that changed this file or directory. A path that never
         *     existed yields an all-zero result rather than a 404. No `follow`
         *     support — unlike the commit log, stats never tracks a path across
         *     renames (docs/DECISIONS.md #59).
         */
        path?: string;
        /**
         * @description Number of authors returned, most active first. Parsed manually so an
         *     invalid value yields the JSON `invalid_param` envelope instead of
         *     axum's plain-text 400. Never clamped.
         * @example 50
         */
        limit?: number;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Commit statistics. An empty repository with no `ref` yields an empty result. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full-sha `ref` */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha `ref` requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatsResults"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — unknown `period`, or bad `limit` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_tag: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Tag name exactly as it appears under `refs/tags` — may itself contain `/`
         * @example v1.0.0
         */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tag detail. Never immutably cached — the URL names a tag ref, not a sha, and a tag can be force-moved onto a different object. */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TagDetail"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_tree: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description Directory path; omit (empty) for the root tree
         * @example src
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory entries, trees first then by name. Immutable caching only when `{ref}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TreeListing"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` (missing or not a directory) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  receive_pack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository directory name **including** the `.git` suffix
         * @example git-compose.git
         */
        repo_git: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `read_only` — always; push via SSH instead. Every HTTP method answers the same way. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  upload_pack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository directory name **including** the `.git` suffix
         * @example git-compose.git
         */
        repo_git: string;
      };
      cookie?: never;
    };
    /** @description upload-pack negotiation pkt-lines. `Content-Encoding: gzip` is inflated by the server. Limits: 8 MiB compressed, 64 MiB inflated. */
    requestBody: {
      content: {
        "application/x-git-upload-pack-request": string;
      };
    };
    responses: {
      /** @description Packfile stream */
      200: {
        headers: {
          /** @description Always `no-cache`; Smart HTTP never uses `ETag` */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/x-git-upload-pack-result": string;
        };
      };
      /** @description `invalid_param` — gzip inflation failed or the inflated body exceeded 64 MiB */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Compressed body over 8 MiB — axum's `DefaultBodyLimit` answers in plain text, not the JSON envelope */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `internal` — upload-pack could not be spawned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  info_refs: {
    parameters: {
      query?: {
        /**
         * @description Must be `git-upload-pack`. `git-receive-pack` is `403 read_only`;
         *     anything else (including the dumb protocol's missing value) is
         *     `400 invalid_param`.
         * @example git-upload-pack
         */
        service?: string;
      };
      header?: never;
      path: {
        /**
         * @description Repository directory name **including** the `.git` suffix
         * @example git-compose.git
         */
        repo_git: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description pkt-line service header followed by the ref advertisement */
      200: {
        headers: {
          /** @description Always `no-cache`; Smart HTTP never uses `ETag` */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/x-git-upload-pack-advertisement": string;
        };
      };
      /** @description `invalid_param` — `service` missing or unsupported */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `read_only` — `service=git-receive-pack` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found` — unknown repository, or a path without the `.git` suffix */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `internal` — upload-pack could not be spawned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
