/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/repos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List repositories
     * @description Served from the scan snapshot ([`crate::cache::ScanCache`]), not the
     *     response cache — the list has no single backing repository, so its `ETag`
     *     is a hash of the serialized body.
     */
    get: operations["list_repos"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Repository summary
     * @description An empty repository (unborn HEAD) still answers `200`, with `head`,
     *     `default_branch` and `last_modified` `null` and both counts 0.
     */
    get: operations["get_repo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/archive/{ref}.{format}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Source archive
     * @description Streams `git archive` output chunked (no `Content-Length`). The ref is
     *     resolved first and only the **full sha** reaches the command line. The
     *     `{ref}.{format}` split is suffix matching: `.tar.gz` first, then `.zip`.
     */
    get: operations["get_archive"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/blame/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Per-line attribution
     * @description `{ref}`/`{path}` split as for the tree endpoint. Rename tracking is not
     *     performed — only moves within the file are attributed, per libgit2
     *     defaults.
     */
    get: operations["get_blame"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/blob/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * File metadata and content
     * @description `{ref}`/`{path}` split as for the tree endpoint. Binary or over-1 MiB files
     *     report `content: null` — fetch the raw endpoint instead.
     */
    get: operations["get_blob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/commits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Commit log
     * @description Cursor-paginated, newest first. Merge commits survive the `path` filter
     *     only when the path differs from **every** parent — an approximation of
     *     `git log -- <path>` simplification.
     */
    get: operations["list_commits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/commits/{sha}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Commit detail
     * @description Superset of a log entry, plus the full message and the first-parent
     *     diffstat. The diffstat has no file cap.
     */
    get: operations["get_commit"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/commits/{sha}/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Structured commit diff
     * @description Unified diff as JSON (file → hunk → line), against the first parent.
     *     Caps: 1000 rendered lines per file (whole hunks are dropped, never cut) and
     *     300 files per response; `additions`/`deletions` stay complete either way.
     */
    get: operations["get_commit_diff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/diff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Two-revision diff
     * @description Arbitrary two-revision diff (`git diff <from> <to>`), the same structured
     *     shape as the per-commit diff plus an uncapped `diffstat`. `?to=X` alone
     *     (no `from`) produces `files` identical to `GET /commits/X/diff`. `from`
     *     and `to` accept anything `resolve_commit` does — branch, tag, sha, or a
     *     `revparse_single` expression such as `main~1`.
     */
    get: operations["get_rev_diff"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/feed.atom": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Atom feed of recent commits
     * @description The 20 most recent commits on HEAD. Absolute URLs are reconstructed from
     *     `X-Forwarded-Proto`/`X-Forwarded-Host`, falling back to `Host`; entry ids
     *     are `urn:sha1:{sha}` so they stay stable across hosts. An empty repository
     *     returns `200` with no entries.
     */
    get: operations["get_feed"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/raw/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Raw file contents
     * @description No size cap. Not routed through the response cache — raw bodies are
     *     unbounded binaries that would crowd out the JSON entries. Non-sha requests
     *     still carry an `ETag` so a 304 saves the transfer (the bytes are re-read
     *     either way). `{ref}`/`{path}` split as for the tree endpoint.
     */
    get: operations["get_raw"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/readme": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * README lookup
     * @description Searches the root tree for `README.md` → `README.rst` → `README.txt` →
     *     `README`, matched case-insensitively. Symlinks and binary or over-1 MiB
     *     candidates are skipped. Rendering is the frontend's job.
     */
    get: operations["get_readme"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/refs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Branches and tags
     * @description Tag targets are peeled to the commit, so an annotated tag reports the
     *     commit sha rather than the tag object.
     */
    get: operations["get_refs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Repository search
     * @description git2 in-process scan across file content, file paths, or commit messages
     *     (docs/DECISIONS.md #26) — not a `git grep` exec or a persistent index.
     *     Every scan is bounded by its own byte/file/commit budget independent of
     *     `limit`; either cap sets `truncated: true`.
     */
    get: operations["get_search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Commit-activity statistics
     * @description Buckets commits into 12 `period`-sized windows anchored on the resolved
     *     commit's authordate (docs/DECISIONS.md #28), plus a per-author breakdown.
     *     git2 in-process scan, same budget approach as search (#26) — not a
     *     persistent index or a `git log` exec.
     */
    get: operations["get_stats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/repos/{repo}/tree/{ref}/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Directory listing
     * @description The `{ref}`/`{path}` boundary is resolved per request by longest-ref
     *     matching (`repo::resolve::resolve_ref_path`), because branch and tag names
     *     may contain `/`; with no match the first segment is taken as the ref.
     *     Omit `{path}` for the root tree.
     */
    get: operations["get_tree"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{repo_git}/git-receive-pack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Push is SSH-only (CLAUDE.md invariant): every method on this path is 403. */
    post: operations["receive_pack"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{repo_git}/git-upload-pack": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload-pack negotiation (clone/fetch)
     * @description Pipes the request body into `git upload-pack --stateless-rpc` and streams
     *     its stdout back chunked. If upload-pack dies mid-stream the status code
     *     cannot change, so the client sees an early EOF.
     */
    post: operations["upload_pack"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/{repo_git}/info/refs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ref advertisement (clone/fetch)
     * @description Spawns `git upload-pack --stateless-rpc --advertise-refs` and prepends the
     *     pkt-line service header. A `Git-Protocol` request header is sanitized and
     *     forwarded as `GIT_PROTOCOL`, so protocol v2 negotiation works.
     */
    get: operations["info_refs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Per-author breakdown (docs/API.md). */
    AuthorStats: {
      author: components["schemas"]["CommitAuthor"];
      /** @description Total commits by this author within the window. */
      commits: number;
      /** @description Parallel to the response's `buckets` — same length and order. */
      buckets: number[];
    };
    /** @description Response of the blame endpoint (docs/API.md). */
    BlameInfo: {
      /** @description Resolved commit sha the file was blamed at. */
      sha: string;
      path: string;
      /** @description libgit2's NUL heuristic, or content that is not valid UTF-8. */
      binary: boolean;
      /** @description `true` past the same 1 MiB cap the blob endpoint applies. */
      too_large: boolean;
      /** @description Total line count; 0 for `binary`, `too_large`, or empty files. */
      lines: number;
      /**
       * @description `start_line` ascending, covering the whole file with no gaps.
       *     Empty for `binary`, `too_large`, or empty files.
       */
      ranges: components["schemas"]["BlameRange"][];
    };
    /** @description One contiguous run of lines attributed to the same commit (docs/API.md). */
    BlameRange: {
      /** @description 1-based, inclusive. */
      start_line: number;
      line_count: number;
      /** @description Sha of the commit the lines are attributed to. */
      sha: string;
      /** @description `None` for non-utf8 commit messages. */
      summary: string | null;
      author: components["schemas"]["CommitAuthor"];
      authored_at: string | null;
      /**
       * @description Path the lines had in the attributed commit, when the file has since
       *     been renamed — `None` when unchanged (or when the path is not valid
       *     UTF-8). Only whole-file renames are tracked; libgit2 follows them the
       *     same way `git blame` does by default.
       */
      orig_path: string | null;
    };
    /** @description Response of the blob endpoint (docs/API.md). */
    BlobInfo: {
      /** @description Resolved commit sha the blob was read from. */
      sha: string;
      path: string;
      /**
       * @description Octal file mode, e.g. `"100644"` (`"120000"` for symlinks).
       * @example 100644
       */
      mode: string;
      /**
       * Format: int64
       * @description Full size in bytes, regardless of `too_large`.
       */
      size: number;
      /** @description libgit2's NUL heuristic, or content that is not valid UTF-8. */
      binary: boolean;
      /** @description `true` past the 1 MiB inline-content cap; fetch the raw endpoint instead. */
      too_large: boolean;
      /**
       * @description UTF-8 content; `None` when `binary` or `too_large`. For a symlink this
       *     is the link target path.
       */
      content: string | null;
    };
    /** @description Branch entry of `GET /api/v1/repos/{repo}/refs` (docs/API.md). */
    BranchRef: {
      /** @example main */
      name: string;
      /** @description Commit sha of the branch tip. */
      target: string;
      /** @description Authordate (RFC 3339) of the branch tip. */
      committed_at: string | null;
    };
    /** @description One time bucket (docs/API.md). */
    BucketStats: {
      /** @description Bucket start, UTC, RFC 3339. Ascending order (oldest first). */
      start: string;
      /** @description Total commits in this bucket, including any authors cut by `limit`. */
      commits: number;
    };
    /**
     * @description Commit author of `GET /api/v1/repos/{repo}/commits` (docs/API.md).
     *     The raw email is never exposed; `email_hash` seeds locally generated avatars.
     */
    CommitAuthor: {
      name: string;
      /**
       * @description sha256 hex of the trimmed, lowercased author email.
       * @example b642b4217b34b1e8d3bd915fc65c4452
       */
      email_hash: string;
    };
    /**
     * @description Commit detail of `GET /api/v1/repos/{repo}/commits/{sha}` (docs/API.md).
     *     Superset of [`CommitInfo`] so the frontend can extend the log entry type.
     */
    CommitDetail: {
      /** @description Full commit sha, even when the request used a branch, tag or short sha. */
      sha: string;
      summary: string | null;
      /** @description Full commit message. `None` for non-utf8 messages. */
      message: string | null;
      author: components["schemas"]["CommitAuthor"];
      committer: components["schemas"]["CommitAuthor"];
      authored_at: string | null;
      committed_at: string | null;
      parents: string[];
      /** @description First-parent diffstat (docs/API.md). */
      diffstat: components["schemas"]["DiffStat"];
    };
    /** @description Structured diff of `GET /api/v1/repos/{repo}/commits/{sha}/diff` (docs/API.md). */
    CommitDiff: {
      sha: string;
      /** @description First parent the diff was computed against; `null` for a root commit. */
      parent: string | null;
      /** @description `true` when files beyond [`MAX_DIFF_FILES`] were omitted. */
      truncated: boolean;
      files: components["schemas"]["FileDiff"][];
    };
    /** @description Log entry of `GET /api/v1/repos/{repo}/commits` (docs/API.md). */
    CommitInfo: {
      /** @description Full commit sha. */
      sha: string;
      /** @description First line of the commit message. `None` for non-utf8 commit messages. */
      summary: string | null;
      author: components["schemas"]["CommitAuthor"];
      /**
       * @description Authordate (RFC 3339). `None` for unrepresentable timestamps.
       * @example 2026-07-01T14:00:00+09:00
       */
      authored_at: string | null;
      parents: string[];
    };
    CommitsPage: {
      commits: components["schemas"]["CommitInfo"][];
      /**
       * @description Opaque token for the next page; `null` on the last page. Pass it back
       *     verbatim as the `cursor` query parameter.
       */
      next_cursor: string | null;
    };
    /** @description Diffstat of `GET /api/v1/repos/{repo}/commits/{sha}` (docs/API.md). */
    DiffStat: {
      files: components["schemas"]["DiffStatFile"][];
      files_changed: number;
      total_additions: number;
      total_deletions: number;
    };
    /** @description Per-file entry shared by the diffstat and the diff (`#[serde(flatten)]`). */
    DiffStatFile: {
      /** @example src/main.rs */
      path: string;
      /** @description Previous path; only set for `renamed`/`copied`. */
      old_path: string | null;
      status: components["schemas"]["DiffStatus"];
      /**
       * @description Always the full count, even when the file's hunks were truncated.
       *     Binary files report 0.
       */
      additions: number;
      /**
       * @description Always the full count, even when the file's hunks were truncated.
       *     Binary files report 0.
       */
      deletions: number;
      binary: boolean;
    };
    /**
     * @description How a file changed between the two trees. Rename detection runs with
     *     libgit2 defaults (renames only, 50% similarity).
     * @enum {string}
     */
    DiffStatus: "added" | "deleted" | "modified" | "renamed" | "copied" | "typechange";
    /**
     * @description What a tree entry points at, derived from its file mode.
     * @enum {string}
     */
    EntryKind: "tree" | "blob" | "symlink" | "commit";
    ErrorBody: {
      /**
       * @description One of `repo_not_found`, `ref_not_found`, `path_not_found`,
       *     `invalid_param`, `read_only`, `not_found`, `internal`.
       * @example repo_not_found
       */
      code: string;
      /**
       * @description Human-readable detail. Internal errors report a generic message; the
       *     cause only goes to the server log.
       * @example repository 'foo' not found
       */
      message: string;
    };
    /** @description Error envelope shared by every failing endpoint (docs/API.md). */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    FileDiff: components["schemas"]["DiffStatFile"] & {
      /**
       * @description `true` when hunks were dropped past [`MAX_FILE_DIFF_LINES`].
       *     `additions`/`deletions` still count the full change.
       */
      truncated: boolean;
      /** @description Empty for binary files. */
      hunks: components["schemas"]["Hunk"][];
    };
    /** @description A file with at least one match (docs/API.md). */
    FileMatch: {
      path: string;
      /**
       * @description Empty for `type=path` matches — the path itself is the match, there is
       *     no line to point at.
       */
      lines: components["schemas"]["LineMatch"][];
    };
    Hunk: {
      /**
       * @description `@@ -a,b +c,d @@ <context>` line without the trailing newline.
       * @example @@ -1,2 +1,2 @@
       */
      header: string;
      /** Format: int32 */
      old_start: number;
      /** Format: int32 */
      old_lines: number;
      /** Format: int32 */
      new_start: number;
      /** Format: int32 */
      new_lines: number;
      lines: components["schemas"]["Line"][];
    };
    Line: {
      origin: components["schemas"]["LineOrigin"];
      /** @description Line content without the trailing newline (lossy utf-8). */
      content: string;
      /**
       * Format: int32
       * @description `null` on added lines.
       */
      old_lineno: number | null;
      /**
       * Format: int32
       * @description `null` on deleted lines.
       */
      new_lineno: number | null;
    };
    /** @description Matched line within a file (docs/API.md). */
    LineMatch: {
      /** @description 1-based line number. */
      line: number;
      /** @description The matching line, truncated to [`MAX_LINE_CHARS`] characters. */
      text: string;
    };
    /**
     * @description Which side of the diff a line belongs to. Other libgit2 origins (EOF
     *     newline markers and the like) are dropped rather than reported.
     * @enum {string}
     */
    LineOrigin: " " | "+" | "-";
    /**
     * @description How the frontend should render the README. Only `markdown` is converted to
     *     HTML; the rest are shown as plain text (docs/DECISIONS.md #11).
     * @enum {string}
     */
    ReadmeFormat: "markdown" | "rst" | "plain";
    ReadmeInfo: {
      /**
       * @description Actual file name as it appears in the tree (case may differ).
       * @example README.md
       */
      path: string;
      format: components["schemas"]["ReadmeFormat"];
      content: string;
    };
    RefsInfo: {
      /** @description Sorted by name ascending; empty for a repository without commits. */
      branches: components["schemas"]["BranchRef"][];
      /** @description Sorted by name ascending. */
      tags: components["schemas"]["TagRef"][];
    };
    /** @description Repository list entry as defined by `GET /api/v1/repos` in docs/API.md. */
    RepoInfo: {
      /**
       * @description Repository name without the `.git` suffix.
       * @example git-compose
       */
      name: string;
      /** @description From the repo config's `[axgit]` section, falling back to `[cgit]`. */
      section: string | null;
      /** @description From the repo config's `[axgit]` section, falling back to `[cgit]`. */
      owner: string | null;
      /** @description From the repo config's `[axgit]` section, falling back to `[cgit]`. */
      description: string | null;
      /** @description `None` for empty repositories (unborn HEAD). */
      default_branch: string | null;
      /**
       * @description Agefile (`info/web/last-modified`), falling back to the HEAD authordate.
       *     RFC 3339. `None` for empty repositories without an agefile.
       * @example 2026-07-24T13:06:00+09:00
       */
      last_modified: string | null;
    };
    /**
     * @description Repository summary as defined by `GET /api/v1/repos/{repo}` in docs/API.md.
     *     Kept separate from [`RepoInfo`] — the list and summary responses are
     *     distinct API contracts.
     */
    RepoSummary: {
      /** @example git-compose */
      name: string;
      section: string | null;
      owner: string | null;
      description: string | null;
      default_branch: string | null;
      /** @example 2026-07-24T13:06:00+09:00 */
      last_modified: string | null;
      /** @description HEAD commit sha. `None` for empty repositories (unborn HEAD). */
      head: string | null;
      branch_count: number;
      tag_count: number;
      /** @description `{clone_url_base}/{name}.git`; `None` when no base is configured. */
      clone_url: string | null;
    };
    ReposResponse: {
      repos: components["schemas"]["RepoInfo"][];
    };
    /**
     * @description Two-revision diff of `GET /api/v1/repos/{repo}/diff` (docs/API.md). A
     *     plain tree-to-tree comparison (`git diff <from> <to>`), not a merge-base
     *     `...` diff.
     */
    RevDiff: {
      /**
       * @description Resolved full sha of the old side. `null` only when `from` was omitted
       *     and `to` is a root commit (the old side is then the empty tree).
       */
      from: string | null;
      /** @description Resolved full sha of the new side. */
      to: string;
      /** @description `true` when files beyond [`MAX_DIFF_FILES`] were omitted. */
      truncated: boolean;
      /** @description The full, uncapped file list — same rule as the commit diffstat. */
      diffstat: components["schemas"]["DiffStat"];
      files: components["schemas"]["FileDiff"][];
    };
    /**
     * @description Requested search variant, echoed back in the response's `type` field.
     * @enum {string}
     */
    SearchKind: "content" | "path" | "message";
    /** @description Response of `GET /api/v1/repos/{repo}/search` (docs/API.md). */
    SearchResults: {
      /**
       * @description Resolved commit sha the search ran against. `None` only for an empty
       *     repository (unborn HEAD) with no explicit `ref`.
       */
      sha: string | null;
      type: components["schemas"]["SearchKind"];
      /**
       * @description `true` when a scan or result budget was hit before the search
       *     finished — the results are a prefix, not necessarily the complete
       *     match set.
       */
      truncated: boolean;
      /** @description `content`/`path` results; empty for `type=message`. */
      files: components["schemas"]["FileMatch"][];
      /**
       * @description `message` results; empty otherwise. Reuses the commit log's shape so
       *     the frontend can render matches the same way as log rows.
       */
      commits: components["schemas"]["CommitInfo"][];
    };
    /**
     * @description Requested bucket size, echoed back in the response's `period` field.
     * @enum {string}
     */
    StatsPeriod: "week" | "month" | "quarter" | "year";
    /** @description Response of `GET /api/v1/repos/{repo}/stats` (docs/API.md). */
    StatsResults: {
      /**
       * @description Resolved commit sha the window is anchored on. `None` only for an
       *     empty repository (unborn HEAD) with no explicit `ref`.
       */
      sha: string | null;
      period: components["schemas"]["StatsPeriod"];
      /**
       * @description `true` when the commit scan budget was hit, or the author list was cut
       *     by `limit` — either way, the results are a prefix.
       */
      truncated: boolean;
      /**
       * @description Number of distinct authors within the window (may exceed
       *     `authors.len()` once cut by `limit`).
       */
      author_count: number;
      buckets: components["schemas"]["BucketStats"][];
      /** @description Sorted by commit count, descending; capped at `limit`. */
      authors: components["schemas"]["AuthorStats"][];
    };
    /** @description Tag entry of `GET /api/v1/repos/{repo}/refs` (docs/API.md). */
    TagRef: {
      /** @example v1.0.0 */
      name: string;
      /** @description Peeled commit sha (not the tag object), so clients can link to the commit. */
      target: string;
      /** @description First line of the tag message. `None` for lightweight tags. */
      annotation: string | null;
      /** @description Tagger date (RFC 3339). `None` for lightweight tags. */
      tagged_at: string | null;
    };
    /** @description Tree entry of the tree endpoint (docs/API.md). */
    TreeEntryInfo: {
      name: string;
      type: components["schemas"]["EntryKind"];
      /**
       * @description Octal file mode, e.g. `"100644"`.
       * @example 100644
       */
      mode: string;
      /**
       * Format: int64
       * @description Object size in bytes; blobs only, `None` otherwise.
       */
      size: number | null;
    };
    TreeListing: {
      /** @description Resolved commit sha the listing was taken from. */
      sha: string;
      /** @description Requested directory path; empty string for the root tree. */
      path: string;
      /** @description Trees first, then by name ascending. */
      entries: components["schemas"]["TreeEntryInfo"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_repos: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository list */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Hash of the response body; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReposResponse"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Repository root could not be scanned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_repo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Repository summary */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RepoSummary"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_archive: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description `tar.gz` or `zip`
         * @example tar.gz
         */
        format: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archive stream (`application/gzip` or `application/zip`). If `git archive` fails mid-stream the response is truncated without a status change. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description `attachment; filename="{repo}-{safe_ref}.{format}"` */
          "Content-Disposition"?: string;
          /** @description **Weak** (`W/"..."`); absent on full-sha requests */
          ETag?: string;
          /** @description Always `nosniff` */
          "X-Content-Type-Options"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/gzip": string;
        };
      };
      /** @description `If-None-Match` matched — no git process is spawned */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — suffix is neither `.tar.gz` nor `.zip` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `internal` — `git archive` could not be spawned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_blame: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description File path
         * @example src/main.rs
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Line ranges covering the whole file. Immutable caching only when `{ref}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlameInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_blob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description File path
         * @example README.md
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Blob metadata and inline content. Immutable caching only when `{ref}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlobInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` (missing, or a directory/submodule) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_commits: {
    parameters: {
      query?: {
        /**
         * @description Branch, tag, or commit sha; HEAD when absent. Ignored when `cursor` is set.
         * @example main
         */
        ref?: string;
        /**
         * @description Only commits that changed this file or directory. A path that never
         *     existed yields an empty list rather than a 404.
         */
        path?: string;
        /**
         * @description `next_cursor` from a previous page. Opaque: a malformed or unknown
         *     value is `400 invalid_param`, not a 404.
         */
        cursor?: string;
        /**
         * @description Parsed manually so an invalid value yields the JSON `invalid_param`
         *     envelope instead of axum's plain-text 400. Never clamped.
         * @example 50
         */
        limit?: number;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of commits. An empty repository with no `ref` yields an empty page. */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitsPage"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `limit` or `cursor` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_commit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /** @description Branch, tag, or commit sha */
        sha: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Commit detail. Immutable caching only when `{sha}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitDetail"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_commit_diff: {
    parameters: {
      query?: {
        /**
         * @description Restrict the diff to one file (literal match, no globbing). A path that
         *     this commit did not touch yields `files: []`, not a 404.
         */
        path?: string;
        /**
         * @description Context lines around each change. Parsed manually so an invalid value
         *     yields the JSON `invalid_param` envelope instead of axum's plain-text
         *     400. Never clamped.
         * @example 3
         */
        context?: number;
        /**
         * @description Ignore whitespace-only changes (`git diff --ignore-all-space`). Line
         *     `content` is unaffected — only which lines/hunks are shown changes.
         * @example 1
         */
        ignorews?: boolean;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /** @description Branch, tag, or commit sha */
        sha: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Structured diff. Immutable caching only when `{sha}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommitDiff"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `context` or `ignorews` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_rev_diff: {
    parameters: {
      query?: {
        /**
         * @description Old side of the comparison (`git diff <from> <to>` — not a merge-base
         *     `...` diff). Defaults to `to`'s first parent (the empty tree for a
         *     root commit).
         * @example main
         */
        from?: string;
        /**
         * @description New side of the comparison. Defaults to `HEAD`.
         * @example feature/x
         */
        to?: string;
        /**
         * @description Restrict the diff to one file (literal match, no globbing). A path
         *     neither side touched yields `files: []`, not a 404.
         */
        path?: string;
        /**
         * @description Context lines around each change. Parsed manually so an invalid value
         *     yields the JSON `invalid_param` envelope instead of axum's plain-text
         *     400. Never clamped.
         * @example 3
         */
        context?: number;
        /**
         * @description Ignore whitespace-only changes (`git diff --ignore-all-space`).
         * @example 1
         */
        ignorews?: boolean;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Two-revision diff. Immutable caching only when every side given resolves to the exact requested string as a full sha. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent when immutable */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevDiff"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — bad `context` or `ignorews` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` (names the offending side) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_feed: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Atom 1.0 feed */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/atom+xml": string;
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_raw: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description File path
         * @example README.md
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File bytes. `Content-Type` is guessed from the extension, falling back to `text/plain; charset=utf-8` or `application/octet-stream`. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          /** @description Always `nosniff` — repository contents are untrusted */
          "X-Content-Type-Options"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_readme: {
    parameters: {
      query?: {
        /**
         * @description Branch, tag, or commit sha; HEAD when absent.
         * @example main
         */
        ref?: string;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The first usable README. Immutable caching only when `ref` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadmeInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found`, `ref_not_found` (including an empty repository), `path_not_found` (no README) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_refs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Branches and tags, each sorted by name */
      200: {
        headers: {
          /** @description `no-cache` */
          "Cache-Control"?: string;
          /** @description Validator-derived; opaque */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefsInfo"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `repo_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_search: {
    parameters: {
      query?: {
        /**
         * @description Fixed-string, case-insensitive query. Trimmed; empty or over 200
         *     characters is `invalid_param`.
         * @example TODO
         */
        q?: string;
        /**
         * @description `content` (default), `path`, or `message`.
         * @example content
         */
        type?: string;
        /**
         * @description Branch, tag, or commit sha; HEAD when absent.
         * @example main
         */
        ref?: string;
        /**
         * @description Parsed manually so an invalid value yields the JSON `invalid_param`
         *     envelope instead of axum's plain-text 400. Never clamped.
         * @example 50
         */
        limit?: number;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Search results. An empty repository with no `ref` yields an empty result. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full-sha `ref` */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha `ref` requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResults"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — missing/oversized `q`, unknown `type`, or bad `limit` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_stats: {
    parameters: {
      query?: {
        /**
         * @description `week`, `month` (default), `quarter`, or `year`.
         * @example month
         */
        period?: string;
        /**
         * @description Branch, tag, or commit sha; HEAD when absent.
         * @example main
         */
        ref?: string;
        /**
         * @description Number of authors returned, most active first. Parsed manually so an
         *     invalid value yields the JSON `invalid_param` envelope instead of
         *     axum's plain-text 400. Never clamped.
         * @example 50
         */
        limit?: number;
      };
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Commit statistics. An empty repository with no `ref` yields an empty result. */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full-sha `ref` */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha `ref` requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatsResults"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — unknown `period`, or bad `limit` */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_tree: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository name without the `.git` suffix
         * @example git-compose
         */
        repo: string;
        /**
         * @description Branch, tag, or commit sha
         * @example main
         */
        ref: string;
        /**
         * @description Directory path; omit (empty) for the root tree
         * @example src
         */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Directory entries, trees first then by name. Immutable caching only when `{ref}` is the resolved full sha (then no `ETag`). */
      200: {
        headers: {
          /** @description `no-cache`, or `public, max-age=31536000, immutable` for a full sha */
          "Cache-Control"?: string;
          /** @description Validator-derived; absent on full-sha requests */
          ETag?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TreeListing"];
        };
      };
      /** @description `If-None-Match` matched the current `ETag` */
      304: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `invalid_param` — `.`, `..`, or an empty path segment */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found`, `ref_not_found`, `path_not_found` (missing or not a directory) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  receive_pack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository directory name **including** the `.git` suffix
         * @example git-compose.git
         */
        repo_git: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description `read_only` — always; push via SSH instead. Every HTTP method answers the same way. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  upload_pack: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description Repository directory name **including** the `.git` suffix
         * @example git-compose.git
         */
        repo_git: string;
      };
      cookie?: never;
    };
    /** @description upload-pack negotiation pkt-lines. `Content-Encoding: gzip` is inflated by the server. Limits: 8 MiB compressed, 64 MiB inflated. */
    requestBody: {
      content: {
        "application/x-git-upload-pack-request": string;
      };
    };
    responses: {
      /** @description Packfile stream */
      200: {
        headers: {
          /** @description Always `no-cache`; Smart HTTP never uses `ETag` */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/x-git-upload-pack-result": string;
        };
      };
      /** @description `invalid_param` — gzip inflation failed or the inflated body exceeded 64 MiB */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found` */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Compressed body over 8 MiB — axum's `DefaultBodyLimit` answers in plain text, not the JSON envelope */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description `internal` — upload-pack could not be spawned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  info_refs: {
    parameters: {
      query?: {
        /**
         * @description Must be `git-upload-pack`. `git-receive-pack` is `403 read_only`;
         *     anything else (including the dumb protocol's missing value) is
         *     `400 invalid_param`.
         * @example git-upload-pack
         */
        service?: string;
      };
      header?: never;
      path: {
        /**
         * @description Repository directory name **including** the `.git` suffix
         * @example git-compose.git
         */
        repo_git: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description pkt-line service header followed by the ref advertisement */
      200: {
        headers: {
          /** @description Always `no-cache`; Smart HTTP never uses `ETag` */
          "Cache-Control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/x-git-upload-pack-advertisement": string;
        };
      };
      /** @description `invalid_param` — `service` missing or unsupported */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `read_only` — `service=git-receive-pack` */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `repo_not_found` — unknown repository, or a path without the `.git` suffix */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description `internal` — upload-pack could not be spawned */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
