//! Handler for the archive endpoint: streams `git archive` output, optionally
//! wrapped in an in-process compressor.
//!
//! `tar.gz` and `zip` are generated by the git binary, not libgit2
//! (docs/DECISIONS.md #2 hybrid approach). `git archive` itself only knows
//! those two compressed formats plus plain `tar`; `tar.bz2`, `tar.xz` and
//! `tar.zst` are produced by streaming `git archive --format=tar`'s stdout
//! through an `async-compression` encoder rather than piping it into an
//! external compressor binary (docs/DECISIONS.md #54) — the runtime image
//! stays `git` + `ca-certificates` either way. Only the resolved full sha is
//! ever passed to the exec, so no user-controlled string reaches the command
//! line.

use std::io;
use std::pin::Pin;
use std::process::Stdio;
use std::task::{Context as TaskContext, Poll};

use async_compression::Level;
use async_compression::tokio::bufread::{BzEncoder, XzEncoder, ZstdEncoder};
use axum::body::Body;
use axum::extract::{Path, State};
use axum::http::{HeaderMap, header};
use axum::response::Response;
use tokio::io::{AsyncRead, AsyncReadExt, BufReader, ReadBuf};
use tokio::process::{ChildStdout, Command};
use tokio::sync::OwnedSemaphorePermit;
use tokio_util::io::ReaderStream;

use super::{
    IMMUTABLE_CACHE_CONTROL, NO_CACHE_CONTROL, if_none_match, not_modified, sanitize_component,
    validator_etag,
};
use crate::error::{ApiError, ErrorResponse};
use crate::repo::{meta, open, resolve};
use crate::state::AppState;

/// cgit pipes `git archive --format=tar` through `bzip2 -c` / `xz -c` /
/// `zstd -c` with no level flag, i.e. each tool's own CLI default. These are
/// pinned to match rather than left at `async-compression`'s `Level::Default`,
/// which is *not* the same for two of the three (bzip2 6 vs the CLI's 9, xz
/// preset 5 vs the CLI's 6) — verified against the crate source, not assumed.
const BZIP2_LEVEL: i32 = 9;
const XZ_PRESET: i32 = 6;
const ZSTD_LEVEL: i32 = 3;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Encoder {
    Bzip2,
    Xz,
    Zstd,
}

/// One archive format: the URL suffix, the `git archive --format` value, the
/// media type, and the post-git encoder (if any). Single source of truth —
/// suffix parsing, `Content-Type`, the filename extension, and the 400
/// message all read from this table, so adding a format is a one-line edit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ArchiveFormat {
    /// URL suffix without the leading dot; also the filename extension.
    ext: &'static str,
    /// Value for `git archive --format`.
    git_format: &'static str,
    content_type: &'static str,
    /// `None` streams git's own output byte-for-byte.
    encoder: Option<Encoder>,
}

/// Order is the order the UI lists formats in; it carries no parsing meaning
/// (`parse_archive_target` matches every suffix in the table, not just the
/// first). Plain `.tar` is deliberately absent — an uncompressed source
/// download is a poor default over HTTP — and so is cgit's `tar.lz`, which
/// has no maintained Rust encoder.
const FORMATS: &[ArchiveFormat] = &[
    ArchiveFormat {
        ext: "tar.gz",
        git_format: "tar.gz",
        content_type: "application/gzip",
        encoder: None,
    },
    ArchiveFormat {
        ext: "tar.bz2",
        git_format: "tar",
        content_type: "application/x-bzip2",
        encoder: Some(Encoder::Bzip2),
    },
    ArchiveFormat {
        ext: "tar.xz",
        git_format: "tar",
        content_type: "application/x-xz",
        encoder: Some(Encoder::Xz),
    },
    ArchiveFormat {
        ext: "tar.zst",
        git_format: "tar",
        // Registered by RFC 8878 §7.1 — unlike bzip2/xz, zstd has an IANA
        // media type, so it's used in place of an `x-` prefix.
        content_type: "application/zstd",
        encoder: Some(Encoder::Zstd),
    },
    ArchiveFormat {
        ext: "zip",
        git_format: "zip",
        content_type: "application/zip",
        encoder: None,
    },
];

/// Repeated verbatim in the `#[utoipa::path]` strings below, which only
/// accept literals — `formats_doc_should_list_every_format` keeps the two in
/// sync.
const SUPPORTED_SUFFIXES_DOC: &str = "`.tar.gz`, `.tar.bz2`, `.tar.xz`, `.tar.zst`, `.zip`";

/// Splits the `{ref}.{format}` wildcard. The ref may contain `/` and dots, so
/// only a known suffix from [`FORMATS`] matches, and the separating `.` is
/// stripped explicitly — that is what keeps a bare `main.tar` (no such
/// format; plain tar isn't offered) from being mistaken for a request. No
/// suffix in the table is itself a suffix of another, so iteration order
/// carries no parsing meaning.
fn parse_archive_target(rest: &str) -> Result<(&str, &'static ArchiveFormat), ApiError> {
    let Some((refname, format)) = FORMATS.iter().find_map(|format| {
        rest.strip_suffix(format.ext)
            .and_then(|head| head.strip_suffix('.'))
            .map(|refname| (refname, format))
    }) else {
        return Err(ApiError::InvalidParam(format!(
            "unsupported archive format in '{rest}' (expected one of {SUPPORTED_SUFFIXES_DOC})"
        )));
    };
    if refname.is_empty() {
        return Err(ApiError::InvalidParam(format!(
            "missing ref in archive path '{rest}'"
        )));
    }
    Ok((refname, format))
}

/// An `AsyncRead` that keeps a concurrency permit alive for as long as it is
/// being read — dropping the response body (client disconnect, or EOF) frees
/// the permit. `Unpin` whenever `R` is, so no pin projection is needed.
struct Guarded<R> {
    inner: R,
    _permit: OwnedSemaphorePermit,
}

impl<R: AsyncRead + Unpin> AsyncRead for Guarded<R> {
    fn poll_read(
        mut self: Pin<&mut Self>,
        cx: &mut TaskContext<'_>,
        buf: &mut ReadBuf<'_>,
    ) -> Poll<io::Result<()>> {
        Pin::new(&mut self.inner).poll_read(cx, buf)
    }
}

fn guarded<R: AsyncRead + Unpin>(inner: R, permit: Option<OwnedSemaphorePermit>) -> Guarded<R> {
    Guarded {
        inner,
        // Only encoder formats acquire a permit; a passthrough format never
        // reaches this function (see `archive_body`), but the type is shared
        // so the three encoder arms don't need three near-identical structs.
        _permit: permit.expect("guarded() is only called for encoder formats"),
    }
}

/// Wraps `git archive` stdout in the format's encoder, if any. `tar.gz` and
/// `zip` are already compressed by git and pass through untouched, without
/// taking a concurrency permit.
///
/// Every arm ends at `Body::from_stream`, whose return type doesn't depend on
/// the concrete reader — so the differing `ReaderStream<…>` types never need
/// a `Box<dyn AsyncRead>` or a hand-written reader enum to unify.
fn archive_body(
    stdout: ChildStdout,
    encoder: Option<Encoder>,
    permit: Option<OwnedSemaphorePermit>,
) -> Body {
    let Some(encoder) = encoder else {
        return Body::from_stream(ReaderStream::new(stdout));
    };
    // The `bufread` encoders need `AsyncBufRead`; `ChildStdout` is only
    // `AsyncRead`. 64 KiB (vs `BufReader`'s 8 KiB default) keeps the pipe
    // read count down on multi-megabyte trees.
    let reader = BufReader::with_capacity(64 * 1024, stdout);
    match encoder {
        Encoder::Bzip2 => Body::from_stream(ReaderStream::new(guarded(
            BzEncoder::with_quality(reader, Level::Precise(BZIP2_LEVEL)),
            permit,
        ))),
        Encoder::Xz => Body::from_stream(ReaderStream::new(guarded(
            XzEncoder::with_quality(reader, Level::Precise(XZ_PRESET)),
            permit,
        ))),
        Encoder::Zstd => Body::from_stream(ReaderStream::new(guarded(
            ZstdEncoder::with_quality(reader, Level::Precise(ZSTD_LEVEL)),
            permit,
        ))),
    }
}

/// Source archive
///
/// Streams `git archive` output chunked (no `Content-Length`). The ref is
/// resolved first and only the **full sha** reaches the command line.
/// `{ref}.{format}` is split by matching a known format suffix.
#[utoipa::path(
    get,
    path = "/api/v1/repos/{repo}/archive/{ref}.{format}",
    tag = "files",
    params(
        ("repo" = String, Path, description = "Repository name without the `.git` suffix", example = "git-compose"),
        ("ref" = String, Path, description = "Branch, tag, or commit sha", example = "main"),
        ("format" = String, Path, description = "One of `tar.gz`, `tar.bz2`, `tar.xz`, `tar.zst`, `zip`", example = "tar.gz"),
    ),
    responses(
        (status = 200, description = "Archive stream (`application/gzip`, `application/x-bzip2`, `application/x-xz`, `application/zstd`, or `application/zip`). `tar.bz2`/`tar.xz`/`tar.zst` are produced by streaming `git archive`'s uncompressed tar output through an in-process encoder. If `git archive` fails mid-stream the response is truncated without a status change — for the three encoder formats this yields a well-formed compressed file wrapping a truncated tar, since the encoder still finalizes its container.",
            content_type = "application/gzip",
            body = String,
            headers(
                ("Content-Disposition" = String, description = "`attachment; filename=\"{repo}-{safe_ref}.{format}\"`"),
                ("X-Content-Type-Options" = String, description = "Always `nosniff`"),
                ("ETag" = String, description = "**Weak** (`W/\"...\"`); absent on full-sha requests"),
                ("Cache-Control" = String, description = "`no-cache`, or `public, max-age=31536000, immutable` for a full sha"),
            ),
        ),
        (status = 304, description = "`If-None-Match` matched — no git process is spawned"),
        (status = 400, description = "`invalid_param` — suffix is none of `.tar.gz`, `.tar.bz2`, `.tar.xz`, `.tar.zst`, `.zip`", body = ErrorResponse),
        (status = 404, description = "`repo_not_found`, `ref_not_found`", body = ErrorResponse),
        (status = 500, description = "`internal` — `git archive` could not be spawned", body = ErrorResponse),
    ),
)]
pub async fn get_archive(
    State(state): State<AppState>,
    Path((name, rest)): Path<(String, String)>,
    headers: HeaderMap,
) -> Result<Response, ApiError> {
    let (refname, format) = parse_archive_target(&rest)?;
    let refname = refname.to_owned();

    let root = state.config.repo_root.clone();
    let block_name = name.clone();
    let block_refname = refname.clone();
    let (git_dir, sha, immutable, validator) = tokio::task::spawn_blocking(move || {
        let repo = open::open_named(&root, &block_name)?;
        let validator = meta::validator(&repo);
        let commit = resolve::resolve_commit(&repo, &block_refname)?;
        let sha = commit.id().to_string();
        let immutable = block_refname == sha;
        Ok::<_, ApiError>((repo.path().to_path_buf(), sha, immutable, validator))
    })
    .await
    .map_err(|err| ApiError::Internal(err.into()))??;

    // Weak ETag: the archive bytes are not guaranteed identical across git
    // invocations, but the content is equivalent for an unchanged validator.
    // A match skips spawning `git archive` (and acquiring an encoder permit)
    // entirely.
    let etag = (!immutable).then(|| format!("W/{}", validator_etag(&validator)));
    if let Some(etag) = &etag
        && if_none_match(&headers, etag)
    {
        return Ok(not_modified(etag));
    }

    // Bounds concurrent bzip2/xz/zstd encoders (see `AppState`); acquired
    // before spawning git so an over-capacity request waits rather than
    // spawning a process it isn't ready to consume from yet. `tar.gz`/`zip`
    // never take a permit — git already did the compression for those.
    let permit = if format.encoder.is_some() {
        Some(
            state
                .archive_encoder_limit
                .clone()
                .acquire_owned()
                .await
                .expect("archive_encoder_limit is never closed"),
        )
    } else {
        None
    };

    let base = format!(
        "{}-{}",
        sanitize_component(&name),
        sanitize_component(&refname)
    );
    let mut child = Command::new("git")
        .arg("--git-dir")
        .arg(&git_dir)
        .arg("archive")
        .arg("--format")
        .arg(format.git_format)
        .arg("--prefix")
        .arg(format!("{base}/"))
        .arg(&sha)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .kill_on_drop(true)
        .spawn()
        .map_err(|err| {
            ApiError::Internal(anyhow::Error::new(err).context("failed to spawn git archive"))
        })?;

    let stdout = child.stdout.take().expect("stdout was configured as piped");
    let mut stderr = child.stderr.take().expect("stderr was configured as piped");

    // Reaper: collects stderr and waits so the child never becomes a zombie.
    // Failures past this point cannot change the status code (headers are
    // already sent); the stream just ends short and the client sees a broken
    // download. A dropped Body closes the pipe and git exits on EPIPE.
    tokio::spawn(async move {
        let mut diagnostics = Vec::new();
        let _ = stderr.read_to_end(&mut diagnostics).await;
        match child.wait().await {
            Ok(status) if status.success() => {}
            outcome => tracing::error!(
                sha,
                ?outcome,
                stderr = %String::from_utf8_lossy(&diagnostics),
                "git archive exited abnormally"
            ),
        }
    });

    let mut response = Response::builder()
        .header(header::CONTENT_TYPE, format.content_type)
        .header(
            header::CONTENT_DISPOSITION,
            format!("attachment; filename=\"{base}.{}\"", format.ext),
        )
        // Repository contents are untrusted input; never let the browser sniff.
        .header(header::X_CONTENT_TYPE_OPTIONS, "nosniff");
    response = match &etag {
        None => response.header(header::CACHE_CONTROL, IMMUTABLE_CACHE_CONTROL),
        Some(etag) => response
            .header(header::ETAG, etag)
            .header(header::CACHE_CONTROL, NO_CACHE_CONTROL),
    };
    response
        .body(archive_body(stdout, format.encoder, permit))
        .map_err(|err| ApiError::Internal(err.into()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_archive_target_should_split_known_suffixes() {
        let (refname, format) = parse_archive_target("main.tar.gz").unwrap();
        assert_eq!(refname, "main");
        assert_eq!(format.ext, "tar.gz");

        let (refname, format) = parse_archive_target("feature/x.zip").unwrap();
        assert_eq!(refname, "feature/x");
        assert_eq!(format.ext, "zip");

        // `.tar.gz` wins over a ref that happens to end in `.gz`.
        let (refname, format) = parse_archive_target("v1.0.tar.gz").unwrap();
        assert_eq!(refname, "v1.0");
        assert_eq!(format.ext, "tar.gz");
    }

    #[test]
    fn every_format_should_round_trip_through_parse() {
        for format in FORMATS {
            let rest = format!("feature/x.{}", format.ext);
            let (refname, parsed) = parse_archive_target(&rest).unwrap();
            assert_eq!(refname, "feature/x");
            assert_eq!(parsed, format);
        }
    }

    #[test]
    fn parse_archive_target_should_reject_unknown_or_empty() {
        for rest in [
            "main",
            // Plain tar is deliberately not offered — must stay rejected.
            "main.tar",
            "main.rar",
            "main.gz",
            "main.xz",
            "main.zst",
            "main.tar.lz",
            ".tar.gz",
            ".zip",
            ".tar.zst",
        ] {
            assert!(
                matches!(parse_archive_target(rest), Err(ApiError::InvalidParam(_))),
                "rest {rest:?} was not rejected"
            );
        }
    }

    #[test]
    fn formats_doc_should_list_every_format() {
        for format in FORMATS {
            assert!(
                SUPPORTED_SUFFIXES_DOC.contains(format.ext),
                "{} missing from SUPPORTED_SUFFIXES_DOC / the #[utoipa::path] strings",
                format.ext
            );
        }
        // `contains` alone wouldn't catch a format removed from the table
        // while its suffix happens to remain a substring of another's doc
        // entry — the backtick count pins the entry count too.
        assert_eq!(
            SUPPORTED_SUFFIXES_DOC.matches('`').count() / 2,
            FORMATS.len()
        );
    }
}
